- hosts: all
  gather_facts: False
  tasks:
    - name: UNinstall additional packages
      apt:
        name: "{{ packages }}"
        state: absent
        purge: true
      vars:
        packages:
        - virtualenv
        - python-dev
        - mysql-server
        - python2.7-mysqldb
        - libmysqlclient-dev
        - nginx
        - python-setuptools
        - build-essential
        - ufw
    - name: remove project dir
      shell: rm -Rf /opt/ormuco
    - name: remove project dir
      shell: rm -Rf /etc/systemd/system/ormuco.service
    #~ - name: remove project dir
      #~ shell: rm -Rf /etc/mysql/mysql.conf.d/mysqld.cnf
    - name: force systemd to reread configs
      systemd:
        daemon_reload: yes
    - name: remove dbhost into /etc/hosts
      lineinfile:
          dest: /etc/hosts
          regexp: '.*dbhost'
          state: absent
